services:
  - type: web
    name: farmacia-digital
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_CLOUDINARY_CLOUD_NAME
        sync: false
      - key: VITE_CLOUDINARY_API_KEY
        sync: false
      - key: VITE_CLOUDINARY_API_SECRET
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
